# -*- coding: utf-8 -*-
"""1. cryptobot_aggregate_sentiment-r1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f_tHTXaM19xiHkjr3hjh9ej7pRsGcy7-
"""

from lumibot.entities import Asset
from lumibot.backtesting import CcxtBacktesting
from lumibot.strategies.strategy import Strategy
from datetime import datetime
from colorama import Fore
import random

# New Imports
from timedelta import Timedelta
from langchain_ollama import OllamaLLM
from ollama import chat
from pydantic import BaseModel
import json
from llmprompts import get_web_deets, prompt_template


class Response(BaseModel):
    sentiment: str
    score: float


class CryptoTrader(Strategy):

    def initialize(self, cash_at_risk: float = 0.2, coin: str = "BTC"):
        self.set_market("24/7")
        self.sleeptime = "1D"
        self.last_trade = None
        self.cash_at_risk = cash_at_risk
        self.coin = coin

    def position_sizing(self):
        cash = self.get_cash()
        last_price = self.get_last_price(
            Asset(symbol=self.coin, asset_type=Asset.AssetType.CRYPTO),
            quote=Asset(symbol="USD", asset_type="crypto"),
        )
        if last_price == None:
            quantity = 0
        else:
            quantity = cash * self.cash_at_risk / last_price
        return cash, last_price, quantity

    # Added date retrieval
    def get_dates(self):
        today = self.get_datetime()
        day_prior = today - Timedelta(days=1)
        return today.strftime("%Y-%m-%d"), day_prior.strftime("%Y-%m-%d")

    # Added sentiment
    def get_sentiment(self):
        today, day_prior = self.get_dates()
        news = get_web_deets(day_prior, today)
        print(Fore.YELLOW + news + Fore.RESET)



        stream = chat(
            model="deepseek-r1:14b",
            messages=[{"role": "user", "content": prompt_template(news)}],
            format=Response.model_json_schema(),
        )
        result = json.loads(stream["message"]["content"])
        print(Fore.LIGHTBLUE_EX + str(result) + Fore.RESET)
        return result

    def on_trading_iteration(self):
        cash, last_price, quantity = self.position_sizing()
        # Get News, Sentiment and Probability
        news_data = self.get_sentiment()
        sentiment = news_data["sentiment"]
        probability = news_data["score"]

        if last_price != None:
            if cash > (quantity * last_price):
                # Remove random choice and add sentiment trading to go with sentiment
                if sentiment == "positive" and probability >= 0.7:
                    if self.last_trade == "sell":
                        self.sell_all()
                    order = self.create_order(
                        Asset(symbol=self.coin, asset_type=Asset.AssetType.CRYPTO),
                        quantity,
                        "buy",
                        type="market",
                        quote=Asset(symbol="USD", asset_type="crypto"),
                    )
                    print(Fore.LIGHTMAGENTA_EX + str(order) + Fore.RESET)
                    self.submit_order(order)
                    self.last_trade = "buy"
                if sentiment == "negative" and probability >= 0.7:
                    if self.last_trade == "buy":
                        self.sell_all()
                    order = self.create_order(
                        Asset(symbol=self.coin, asset_type=Asset.AssetType.CRYPTO),
                        quantity,
                        "sell",
                        type="market",
                        quote=Asset(symbol="USD", asset_type="crypto"),
                    )
                    print(Fore.LIGHTMAGENTA_EX + str(order) + Fore.RESET)
                    self.submit_order(order)
                    self.last_trade = "sell"


if __name__ == "__main__":
    start_date = datetime(2023, 10, 1)
    end_date = datetime(2024, 11, 1)
    exchange_id = "kraken"
    kwargs = {
        "exchange_id": exchange_id,
    }
    CcxtBacktesting.MIN_TIMESTEP = "day"

    results, strat_obj = CryptoTrader.run_backtest(
        CcxtBacktesting,
        start_date,
        end_date,
        benchmark_asset="BTC/USD",
        quote_asset=Asset(symbol="USD", asset_type="crypto"),
        parameters={"cash_at_risk": 0.25, "coin": "BTC"},
        **kwargs,
    )